export type LangBlock={en:string,he?:string,fr?:string}
export type Service={id:string,icon:string,title:LangBlock,body:{challenges:LangBlock,solution:LangBlock,benefits:LangBlock}}
export const services:Record<string,Service>={
 security:{id:'security',icon:'🔐',title:{en:'Security & Safety'},body:{challenges:{en:'Nationality crime, theft, vandalism, unauthorized access, safety risks and more.'},solution:{en:'Live & proactive human-led monitoring + AI analytics to detect anomalies, enforce access rules, and prevent escalation. Small dedicated teams provide individual attention and full operational flexibility.'},benefits:{en:'• Reduce dependency on physical security forces and costs.\n• “Eyes on the ground” at all times with immediate insight.\n• Prevent incidents proactively using existing cameras.\n• Integrate AI for custom alerts matched to your risks.'}}},
 qa:{id:'qa',icon:'✅',title:{en:'Quality Assurance'},body:{challenges:{en:'Operational inconsistencies, overlooked errors, lack of accountability, and gaps in compliance with safety and service standards.'},solution:{en:'Dedicated monitoring and day-to-day reviews ensure processes align with SOPs. Observers document deviations, guide staff in real time, and provide structured insights.'},benefits:{en:'• Cost avoidance via early error detection.\n• Strengthened compliance with internal and external standards.\n• Continuous feedback loop that improves efficiency and accountability.\n• Higher service quality and reduced rework.'}}},
 lobby:{id:'lobby',icon:'🛎️',title:{en:'Remote Lobby Services'},body:{challenges:{en:'Unmanned entrances, uncontrolled visitor access, delivery management, and unauthorized entry attempts.'},solution:{en:'Centralized remote operators verify identities, manage visitor flows, log deliveries, and guide guests via live video and intercom — consistent access control without on-site staffing.'},benefits:{en:'• Lower staffing costs without compromising safety.\n• Consistent, professional visitor experience.\n• Enhanced security with verified entry and auditable logs.\n• Scales across multiple properties from one hub.'}}},
 process:{id:'process',icon:'🧩',title:{en:'Process Control'},body:{challenges:{en:'Critical processes breaking down due to lack of oversight, unsafe practices, or late detection of deviations.'},solution:{en:'Monitoring teams continuously observe operations to ensure compliance with SOPs. Smart alerts and structured reporting escalate issues in real time while coaching teams to maintain discipline.'},benefits:{en:'• Immediate detection of unsafe or incorrect practices.\n• Reduced operational risks and improved workplace safety.\n• Increased accountability via real-time reporting.\n• Protection of project timelines and prevention of delays.'}}},
 safeaway:{id:'safeaway',icon:'🧭',title:{en:'SafeAway'},body:{challenges:{en:'If you are away (vacation, event, etc.), you are concerned about leaving the house or business unattended.'},solution:{en:'After a short registration, we connect to your cameras and monitor your home or business according to your needs. If anything unusual occurs, we inform you immediately. Hourly or daily coverage.'},benefits:{en:'• Protect your assets in a real and high-quality manner.\n• Peace of mind — not just analytics alerts, but human visual inspection and scanning.\n• Immediate escalation in case of emergencies or suspicious activity.\n• Flexible coverage — continue or stop anytime.'}}}
}
